### ISSUE TITLE
App crash due to error throw

### ISSUE THREAD

**Issue by icedtrees** [icedtrees/drawn-together#104]
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: read ECONNRESET
        at exports._errnoException (util.js:746:11)
        at TCP.onread (net.js:559:26)
    [nodemon] app crashed - waiting for file changes before starting...

**Comment by icedtrees** [comment]
Might be fixed by https://github.com/icedtrees/drawn-together/commit/eebe3ef09a422aa4bf8d8e46f1a55a1096585c81

**Comment by cloudier** [comment]
Is this fixed by https://github.com/icedtrees/drawn-together/pull/112?

**Comment by icedtrees** [comment]
this is a different crash, it's when the server arbitrarily dies due to a client tcp disconnect. The server does not recover and we have to go in and manually kick the server.

**Comment by icedtrees** [comment]
I think this might have been fixed by https://github.com/icedtrees/drawn-together/commit/eebe3ef09a422aa4bf8d8e46f1a55a1096585c81, but it's hard to know because I don't see any logging messages frmo the commit. Going to close this out for now and pray that it doesn't come bac
